# Generated by Django 3.2.6 on 2021-09-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('Casablanca', 'Casablanca'), ('Rabat', 'Rabat'), ('Settat', 'Settat')], default='Casablanca', max_length=12),
        ),
    ]
